import { Autocomplete, Box, Button, Chip, Container, Grid, Stack, TextField } from "@mui/material";
import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import React from "react";
import { useImmer } from "use-immer";
import { Letter } from "../components/letter";
import styles from "../styles/Home.module.css";
import { createGuessFromWord, Guess, Result } from "../utils/create-guess-from-word";
import { include, includeAtPosition, notInclude, notIncludeAtPosition } from "../utils/filters";
import { Filter, filterWordList } from "../utils/filter-word-list";
import { loadWordlist } from "../utils/load-words";
import { sortWords } from "../utils/sort-words";
import { createFilterList } from "../utils/create-filter-list";

const lastResult = Object.values(Result).pop()

const stylesForLetter = {
  [Result.Invalid]: {
    backgroundColor: 'red',
    color: 'white'
  },
  [Result.Orange]: {
    backgroundColor: 'orange',
    color: 'white'
  },
  [Result.Green]: {
    backgroundColor: 'green',
    color: 'white'
  }
}

const wordList = sortWords(loadWordlist() ?? [])


const Home: NextPage = () => {
  const [guesses, setGuesses] = useImmer<Guess[]>([]);
  const [words, setWords] = useImmer<string[]>(wordList ?? [])
  
  const addWord = React.useCallback((word: string) => {
    setGuesses(existing => {
      existing.push(createGuessFromWord(word))
    })
  }, [setGuesses])
  
  const toggleGuessState = React.useCallback((guessNumber: number, charIndex: number) => {
    setGuesses(existing => {
      let resultValue = existing[guessNumber][charIndex].result
      if (resultValue === lastResult) {
        existing[guessNumber][charIndex].result = Result.Invalid
        return
      }
      existing[guessNumber][charIndex].result = resultValue + 1
    })
  }, [setGuesses])

  React.useEffect(() => {
    setWords(sortWords(filterWordList(wordList ?? [], createFilterList(guesses))))
  }, [guesses, setWords])

  return (
    <Container>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Grid container spacing={1}>
        {guesses.map((guess, guessNumber) => <Grid item xs={12} key={guessNumber}>
          <Stack direction={'row'} spacing={1}>
            {guess.map((char, charIndex) => <Box key={charIndex} sx={{...stylesForLetter[char.result], width: 20, textAlign: 'center'}} onClick={() => toggleGuessState(guessNumber, charIndex)}>{char.letter}</Box>)}
          </Stack>
        </Grid>)}
        <Grid item xs={12}>

        </Grid>
        <Grid item xs={12}>
          <Grid container spacing={1} sx={{marginBottom: 2}}>
              {words.slice(0, 20).map(word => <Grid item key={word}><Chip key={word} label={word} onClick={() => addWord(word)} variant="outlined"/></Grid>)}
          </Grid>
        </Grid>
        <Grid item xs={12}>
          <Autocomplete
            disablePortal
            options={words}
            sx={{ width: 300 }}
            onChange={(event, value) => value && addWord(value)}
            renderInput={(props) => {
              console.log(props)
              return <TextField {...props} />
            }}
          />
        </Grid>
      </Grid>
    </Container>
  );
};

export default Home;
